[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["chrono"] }
tracing-appender = { workspace = true }
thiserror = { workspace = true }
#tracing-core = { workspace = true }
