port = 80
worker_threads = 256
dst_read_timeout = 120000
dst_write_timeout = 120000
rsa_dir = "resources/proxy/rsa"
max_log_level = "INFO"
dst_buffer_size = 8388608
agent_buffer_size = 8388608
server_socket_recv_buffer_size = 262144
server_socket_send_buffer_size = 262144