port = 80
worker_threads = 256
dst_read_timeout = 20
dst_write_timeout = 20
rsa_dir = "resources/proxy/rsa"
max_log_level = "INFO"
dst_buffer_size = 8388608
agent_buffer_size = 8388608
agent_connection_write_timeout = 20
agent_connection_read_timeout = 20
agent_connection_tcp_keep_alive = 120
server_socket_backlog = 1024
dst_connect_timeout = 20
dst_tcp_keepalive = 120