port = 80
worker_threads = 512
rsa_dir = "resources/proxy/rsa"
max_log_level = "ERROR"
dst_buffer_size = 65536
agent_buffer_size = 65536
#agent_connection_write_timeout = 120
#agent_connection_read_timeout = 120
agent_connection_tcp_keepalive = true
agent_connection_tcp_keepalive_interval = 75
agent_connection_tcp_keepalive_time = 7200
agent_connection_tcp_keepalive_retry = 9
#agent_socket_send_buffer_size = 16384
#agent_socket_receive_buffer_size = 87380
server_socket_backlog = 1024
dst_connect_timeout = 20
#dst_read_timeout = 120
#dst_write_timeout = 120
dst_tcp_keepalive_interval = 75
dst_tcp_keepalive_time = 7200
dst_tcp_keepalive_retry = 9
#dst_socket_send_buffer_size = 16384
#dst_socket_receive_buffer_size = 87380
forward_rsa_dir = "resources/proxy/forward_rsa"
#forward_server_addresses = ["127.0.0.1:90"]
#forward_auth_token = "proxy_forward_user1"