port = 90
worker_threads = 256
dst_read_timeout = 120
dst_write_timeout = 120
rsa_dir = "resources/proxy/rsa"
max_log_level = "INFO"
dst_buffer_size = 65536
agent_buffer_size = 65536
agent_connection_write_timeout = 120
agent_connection_read_timeout = 120
agent_connection_tcp_keepalive = false
agent_connection_tcp_keepalive_interval = 75
agent_connection_tcp_keepalive_time = 7200
agent_connection_tcp_keepalive_retry = 9
server_socket_backlog = 1024
dst_connect_timeout = 20
dst_tcp_keepalive_interval = 75
dst_tcp_keepalive_time = 7200
dst_tcp_keepalive_retry = 9
#forward_server_addresses = ["127.0.0.1:80"]
#forward_auth_token"user2"