[package]
name = "proxy"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/bin/entry.rs"
name = "ppaass-v2-proxy"
[lib]
path = "src/lib.rs"

[dependencies]
ppaass-v2-domain = { path = "../domain", package = "domain" }
anyhow = { workspace = true }
derive_more = { workspace = true, features = ["full"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true, features = ["chrono"] }
chrono = { workspace = true }
serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }
clap = { workspace = true, features = ["derive"] }
tokio-util = { workspace = true, features = ["codec"] }
futures-util = { workspace = true, features = ["sink"] }
bytes = { workspace = true }
bincode = { workspace = true }