port = 10090
auth_token = "user1"
worker_threads = 256
rsa_dir = "resources/agent/rsa"
#proxy_addresses = ["64.176.10.101:80"]
#proxy_addresses = ["45.76.0.10:80"]
proxy_addresses = ["192.168.31.254:80"]
#proxy_addresses = ["127.0.0.1:80"]
max_log_level = "DEBUG"
client_relay_buffer_size = 65536
proxy_relay_buffer_size = 65536
proxy_connection_pool_size = 32
proxy_connection_check_interval = 60
proxy_connection_pool_fill_interval = 20
proxy_connect_timeout = 20
proxy_connection_tcp_keepalive = false
#proxy_connection_read_timeout = 120
#proxy_connection_write_timeout = 120
#proxy_socket_send_buffer_size = 16384
#proxy_socket_receive_buffer_size = 87380
# proxy_connection_tcp_keepalive_interval = 75
# proxy_connection_tcp_keepalive_time = 7200
#client_socket_send_buffer_size = 16384
#client_socket_receive_buffer_size = 87380
client_connection_tcp_keepalive = false
# client_connection_tcp_keepalive_interval = 75
# client_connection_tcp_keepalive_time = 7200
server_socket_backlog = 1024
#client_connection_read_timeout = 120
#client_connection_write_timeout = 120
proxy_connection_start_check_timer = true
proxy_connection_start_check_timer_interval = 60
proxy_connection_max_lifetime = 300
proxy_connection_max_ping_pong_time = 10
proxy_connection_ping_pong_read_timeout = 10
proxy_connection_retake_interval = 1
log_folder = "logs"
worker_thread_keep_alive = 5
server_event_max_size = 65536
