port = 10090
auth_token = "user1"
worker_threads = 256
rsa_dir = "resources/agent/rsa"
#proxy_addresses = ["64.176.10.101:80"]
proxy_addresses = ["127.0.0.1:80"]
max_log_level = "DEBUG"
client_relay_buffer_size = 8388608
proxy_relay_buffer_size = 8388608
proxy_connection_pool_size = 32
proxy_connection_check_interval = 120
proxy_connection_pool_fill_interval = 20
