port = 10090
auth_token = "user1"
worker_threads = 256
rsa_dir = "resources/agent/rsa"
#proxy_addresses = ["45.32.10.177:80"]
proxy_addresses = ["127.0.0.1:8080"]
max_log_level = "DEBUG"
client_relay_buffer_size = 8388608
proxy_relay_buffer_size = 8388608
proxy_connection_pool_size = 32
proxy_socket_recv_buffer_size = 8388608
proxy_socket_send_buffer_size = 8388608