port = 10090
auth_token = "user1"
worker_threads = 256
rsa_dir = "resources/rsa"
proxy_create_session_entry = "http://45.76.0.10:8080/session/create"
proxy_relay_entry = "ws://45.76.0.10:8080/relay"
max_log_level = "INFO"
client_buffer_size = 8388608
