port = 10080
auth_token = "user1"
worker_threads = 256
rsa_dir = "resources/agent/rsa"
#proxy_addresses = ["64.176.10.101:80"]
proxy_addresses = ["45.76.0.10:80"]
max_log_level = "DEBUG"
client_relay_buffer_size = 8388608
proxy_relay_buffer_size = 8388608
proxy_connection_pool_size = 32
proxy_connection_check_interval = 60
proxy_connection_pool_fill_interval = 20
proxy_connect_timeout = 20
proxy_connection_read_timeout = 20
proxy_connection_write_timeout = 20
proxy_connection_tcp_keepalive_interval = 75
proxy_connection_tcp_keepalive_time = 7200
proxy_connection_tcp_keepalive_retry = 9
client_connection_tcp_keepalive_interval = 75
client_connection_tcp_keepalive_time = 7200
client_connection_tcp_keepalive_retry = 9
server_socket_backlog = 1024
client_connection_read_timeout = 20
client_connection_write_timeout = 20